spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 34976814883-q0ijo8r4jq19focd3los020hcqb7a8c9.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 196415669976856
            client-secret: 8a6118926a48e4b3f32d83f43dc0ecee

  server:
    port: 8080